###############################################################
#
# Config File for INVISIBLE UNIVERSITY flavour of VITALITY bootstrap theme
#
#--------------------------------------------------------------
BaseURL = "https://maarjaurb.github.io/frukonstnar/"
LanguageCode = "se-SE"
Title = "Frü Konstnär"
Theme = "hugo-university-theme"
publishDir = "docs"

[Params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.

  Flavour = "university"
	Style = "modern"

	# !Important: Theme colors can be selected in static/less/vitality.less
	
	Name = "Frü Konstnär"
	Description = "..."
	Favicon = "favicon.ico"
	Author = "HOMEY PAGES (homey.berlin)"
	Brand = "Frü Konstnär"

	# List of Google fonts, for use in less files.
	#
	# TIPP! To find fonts:
	# - Go to fonts.google.com.
	# - Select a font, open the selected font at the bottom of the page, maybe customize it
	# - In section "Embed Font" copy the full family value (boldly printed), everything after 'family='.
	# - Add it in quotation marks to the list below.
	#
	# TIPP! A good first step after defining fonts, would be to go to static/less/vitality.less and define the main fonts.

	Fonts = [
		"IM+Fell+English+SC&amp;subset=latin-ext",
		"Josefin+Sans:300,300i,400,400i,700,700i",
		"Roboto:100,400,500,700,700i"
	]

	# If you want to have your fonts local, you have to place them in static/fonts folder
	FontsLocal = true
